name: Blueprint Upload to S3

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm install

      - name: Run aglio
        run: npx gulp

      - name: Upload file to S3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: aws s3 sync ./pub/api/* s3://$S3_UPLOAD_BUCKET/ --quiet
